### PR TITLE
No eavesdropping 🙂

### PR DESCRIPTION
**Pull request by ifedapoolarewaju**

### CODE REVIEW

**Comment by rmehner** [comment]
👍  This is *really* important, I wonder why this slipped in all reviews. Can you please add that to the changelog and I'll issue another release. I even think this is worth backporting to a pre-2.x release.

**Comment by tim-kos** [comment]
Yep, definitely worth back porting. Let's not make compromises on security.

**Comment by ifedapoolarewaju** [comment]
@rmehner done!

**Comment by rmehner** [comment]
[2.0.1 has been released](https://rubygems.org/gems/transloadit/versions/2.0.1)

🙏 @ifedapoolarewaju

**Pull request merged**
