### PR TITLE
Remove bored instance logic

### PR DESCRIPTION
**Pull request by ifedapoolarewaju**

### CODE REVIEW

**Comment by tim-kos** [comment]
Hey @rmehner,

We have hired @ifedapoolarewaju to audit the Ruby SDK (and other SDKs) a bit and make some changes to it. Since the bored logic is no longer required, this first PR is about removing it. Could you please review the changes? To me they look fine, but definitely needs some Ruby eyeballs.

Also do you have an idea why Travis would crap out over a Rake update, which is not part of this PR?

**Comment by rmehner** [comment]
Thanks @ifedapoolarewaju :)

> Also do you have an idea why Travis would crap out over a Rake update, which is not part of this PR?

This is mostly because we're still testing on some outdated and EOL'd Ruby versions. Since there is #29 open as issue, we'll move to more current versions now. People who need old ruby version support still can use 1.2.0, they just have to use specify it that way in their installations. I'll add a note about this in the README and will issue a 2.x release to mark a breaking change according to semver.

The tests shouldn't fail on current Ruby versions though, but they do for some seeds, e.g.: `SEED=10496 bundle exec rake test` fails reliably on Ruby 2.3.1. Same for: `SEED=37550 bundle exec rake test`

@ifedapoolarewaju do you have some time to check those errors out and fix them? Don't worry about older Ruby versions, 2.3.x is enough for now :)

**Comment by ifedapoolarewaju** [comment]
@rmehner sure! I already have it on my checklist. So far the only notable difference for the test failures is the removal of cassette [here](https://github.com/transloadit/ruby-sdk/pull/28/files#diff-2fd57a5e9ef810c32a9e6cb340ae3639R95) and the change of the API url [here](https://github.com/transloadit/ruby-sdk/pull/28/files#diff-2fd57a5e9ef810c32a9e6cb340ae3639R101). Do you maybe have any idea why that may be the cause?

**Comment by rmehner** [comment]
If you rebase master, you'll get rid of the older versions btw :)

> Do you maybe have any idea why that may be the cause?

As it runs with some seeds and not some others, I think it's because of something that sets something on the class and doesn't get properly reset. I'd need to debug this as well. What I would do is:

1. Note the seed mentioned above.
2. Pick a reporter that shows the full test name before run
3. See what tests run before the failure.
4. Slowly comment them out until I find the test that causes the state for the followup test
5. *magic*

:)

**Comment by ifedapoolarewaju** [comment]
Thank you for the hint! 😃 Would take a look at it this week.

**Comment by rmehner** [comment]
Alright, let me know if you need any help, will do my best in supporting you :)

**Comment by tim-kos** [comment]
Thank you @rmehner <3

**Comment by ifedapoolarewaju** [comment]
Hi @rmehner :) Failing test fixed!

**Pull request merged**
